services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"

  db:
    image: postgres:14.1-alpine
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  api:
    container_name: api
    build:
      context: ./backend
      dockerfile: api.Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
      - db
    volumes:
      - shared-volume:/app/files/shared

  celery:
    container_name: celery
    build:
      context: ./backend
      dockerfile: celery.Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - shared-volume:/app/files/shared
    depends_on:
      - rabbitmq

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - api

volumes:
  postgres_volume:
  shared-volume:
