services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"

  db:
    image: postgres:14.1-alpine
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  api:
    container_name: api
    build:
      context: ./backend
      dockerfile: api.Dockerfile
    ports:
      - "443:8000"
    depends_on:
      - rabbitmq
      - db
    volumes:
      - shared-volume:/app/files/shared
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672
      - DATABASE_URL=postgresql://postgres:postgres@db:5432

  celery:
    container_name: celery
    build:
      context: ./backend
      dockerfile: celery.Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - shared-volume:/app/files/shared
    depends_on:
      - rabbitmq
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672
      - DATABASE_URL=postgresql://postgres:postgres@db:5432

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - api
    environment:
      - internalApiUrl=http://api:8000
      - externalApiUrl=http://10.212.26.20:443

volumes:
  postgres_volume:
  shared-volume:
