---
version: '3'




services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq-master
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
      
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  a1:
    build: 
      context: ../
      dockerfile: ./containers/Dockerfile.a1
    container_name: a1
    depends_on:
      - rabbitmq

  a2:
    build: 
      context: ../
      dockerfile: ./containers/Dockerfile.a2
    container_name: a2
    depends_on:
      - rabbitmq

volumes:
  mongodb_data_container:
    
networks:
  default:
    driver: bridge
  
