FROM python:3

WORKDIR /usr/src/app


COPY /src/mq_services/globals /usr/src/app/.
COPY /src/mq_services/analyzers/a1 /usr/src/app/.

RUN pip install --no-cache-dir -r global_requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

CMD [ "python", "./git_analyzer.py" ]

