---
version: '3'


services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq-master
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672" 
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - postgres_volume:/var/lib/postgresql/data
  
  # celery_worker:
  #   image: python:3.11
  #   command: bash -c "pip install -r requirements.txt && celery -A your_celery_app worker --loglevel=info"
  #   volumes:
  #     - ./backend/:/app
  #   depends_on:
  #     - rabbitmq
  #     - db
  #   environment:
  #     - CELERY_BROKER_URL="amqp://guest:guest@rabbitmq:5672/%2F"
  #     - DATABASE_URL="postgresql://postgres:postgres@db"
  #   working_dir: /app

volumes:
  postgres_volume:
