---
version: '3'


services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq-master
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672" 
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - postgres_volume:/var/lib/postgresql/data
  
volumes:
  postgres_volume:
